### ISSUE TITLE
[Off Canvas] Closing feature

### ISSUE THREAD

**Issue by acespace90** [frend/frend.co#111]
Is it possible to disable the closing when you click outside the off canvas. I want the only way to close the component is when you press on the close button.
Thanks.

**Comment by adamduncan** [comment]
Hey @acespace90, it's not currently possible, although adding an option in the API might be a nice way of achieving this. `preventClickOutside` or `preventDocumentClick` 🤔 as a boolean, `false` by default? What do you think?

**Comment by acespace90** [comment]
It would be great.

**Comment by adamduncan** [comment]
Cool. How does this look #112?

**Comment by acespace90** [comment]
Thank you @adamduncan

**Comment by adamduncan** [comment]
No problem, @acespace90. That's out in [Offcanvas 1.1.0](https://www.npmjs.com/package/fr-offcanvas) and [docs](https://frend.co/components/offcanvas/#options). Enjoy

**Comment by acespace90** [comment]
@adamduncan It doesn't seem to work.

See this codepen: https://codepen.io/acespace90/pen/daBWeY

Moreover the transition for opening and closing doesn't work. What am I wrong?

**Comment by adamduncan** [comment]
@acespace90, you're correct. I neglected to publish the distribution script as part of v1.1.0 🤦‍♂️ It's been a while since we've done the publish dance on this project... 

Have patched the fix through in [v1.1.1](https://www.npmjs.com/package/fr-offcanvas/v/1.1.1), which now properly includes `preventClickOutside`.

[Here's a forked version of your Pen](https://codepen.io/adamduncan/pen/PLoVzL), with the option set (remember this is done during `Froffcanvas()` construction, not as part of the `init()` method) and the necessary CSS for a open/close transition (we consider this a user-/project-specific feature, so don't include these declarations as part of the base offcanvas.css).

Cheers for your patience
