### ISSUE TITLE
by pass bugs

### ISSUE THREAD

**Issue by goetsu** [frend/frend.co#73]
Hi,

currently safari still has a bug, internal links doesn't work if target doesn't have a tabindex="-1".
So if you want that your script work everywhere you need to had this attribut to the target of the links before to move the focus on it with javascript

**Comment by thomasdigby** [comment]
Is this on OSX?

**Comment by goetsu** [comment]
yes and in was in chrome too until last version released

**Comment by thomasdigby** [comment]
Ok, I'll check it out tonight and update the docs to include a tabindex by default.

**Comment by adamduncan** [comment]
I'm doing some minor error handling fixes (#84) over on [enhancements/bypass-links-target](https://github.com/frend/frend.co/tree/enhancement/bypass-links-target).

While that branch is open, thinking we should address this issue too. Been doing a bit more reading, and as @goetsu said, it's been [recently fixed in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=454172#c22), but this [test case](https://jsfiddle.net/f8x1a8ww/1/) is still broken in Safari.

The example component on the site _does_ have `tabindex="-1"` on each anchor by default. Does this mean we just need to update the code example and docs to explain that tabindex is required and the reasons why?

**Comment by adamduncan** [comment]
Resolved tabindex issues (included as default) with #86 PR. Closing, to revisit as browser implementations are normalised.
